chore: bump package dependencies

diff --git a/.github/workflows/continuous-integration-and-deployment.yml b/.github/workflows/continuous-integration-and-deployment.yml
--- a/.github/workflows/continuous-integration-and-deployment.yml
+++ b/.github/workflows/continuous-integration-and-deployment.yml
@@ -2,6 +2,7 @@ name: Deploy application
 permissions: write-all
 
 on:
+  workflow_dispatch:
   push:
     tags:
       - v*
@@ -15,6 +16,13 @@ jobs:
       cancel-in-progress: true
 
     steps:
+      - name: Check if the type is 'tag'
+        if: ${{ github.event_name == 'workflow_dispatch' && github.ref_type != 'tag' }}
+        run: |
+          echo "::error::Workflow needs to be dispatched from a tag"
+          exit 1
+        shell: bash
+
       - name: Checkout
         uses: actions/checkout@v3.3.0
 
@@ -51,6 +59,7 @@ jobs:
           NEXT_PUBLIC_APP_VERSION: ${{ steps.get-version-from-tag.outputs.replaced }}
 
       - name: Create release
+        if: ${{ github.event_name != 'workflow_dispatch' }}
         uses: ncipollo/release-action@v1.12.0
         with:
           name: Version ${{ steps.get-version-from-tag.outputs.replaced }}
